### ISSUE TITLE
Correct information about source version

### ISSUE THREAD

**Issue by oshytiko** [liangjingkanji/JetBrainsMono-patch#1]
Hej 👋

Your README says the patch is based on `v2.251`, but there is no such version just yet, should it be `v2.241` instead?

Would be nice to have this fixed, just for the sake of avoiding confusion :)

**Comment by liangjingkanji** [comment]
[An unreleased version](https://github.com/JetBrains/JetBrainsMono/commit/9a01623903be1c12fc1a14ea3801e42e004f4223)

**Comment by liangjingkanji** [comment]
See https://github.com/JetBrains/JetBrainsMono/issues/547, because the author plans to publish `2.300`

**Comment by oshytiko** [comment]
Got it!! Thank you!!!
