### ISSUE TITLE
What do you think about slashed zero?

### ISSUE THREAD

**Issue by oshytiko** [liangjingkanji/JetBrainsMono-patch#2]
Hej again 👋,

Really like your patch, especially for proper letter `g`, is it possible to add slashed zero for your patch as well?

I know it's exposed as a OpenType feature, but it would be nice to have it enabled by default. 

I know how to frieze font features with a `python` script, and wanted to do it myself, but then I stumbled upon the fact I cannot understand how did you implemented your patches, did you re-draw the letters or picked them from somewhere? Double-story `g` looks awful lot like a Fira Code to me...

Anyhow... May I ask you to create one more patch, that will add slashed zero by default? If it's not a big hassle for you of couse.

Many thanks in advance!

**Comment by liangjingkanji** [comment]
1. I don't care, But I'll modify slashed zero when I have time
2. Can OpenType achieve multiple glyphs coexisting? 
3. I use `Glyphs` application modify font

Are you talking about patch1 or path2?  I now use `g` of patch2, I don't like `g` of Fira-code now

**Comment by oshytiko** [comment]
I'm a fan of open double story (Fira Code style) `g` it makes `JetBrains Mono` usable for me. 

There is an effort to switch slashed and dotted zero features for `JetBrains Mono`: https://github.com/sharpjs/JetBrainsMonoSlashed (so slashed is the default one and dotted is optional)

**Comment by liangjingkanji** [comment]
JetBrains IDE don't know how to discover and enable OpenType features

**Comment by oshytiko** [comment]
Wow, didn't know that it's such an issue for IDEA... https://youtrack.jetbrains.com/issue/IDEA-221886/Support-stylistic-sets-for-fonts

**Comment by liangjingkanji** [comment]
I can't continue trial Glyphs2 (I don't support the purchase way), so the font cannot be edited

Because to the Glyphs2 used by Jetbrains-Mono, fonts cannot be exported with Glyphs3

**Comment by liangjingkanji** [comment]
May be you can try [v2.251-patch3](https://github.com/liangjingkanji/JetBrainsMono-patch/releases/tag/v2.251-patch3)

Contain slashed zero
